"""update Player.username to be unique

Revision ID: 4c7e5ef457
Revises: a0e4b2c067
Create Date: 2015-04-15 23:03:22.451281

"""

# revision identifiers, used by Alembic.
revision = '4c7e5ef457'
down_revision = 'a0e4b2c067'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_players_username', table_name='players')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_players_username', 'players', ['username'], unique=False)
    ### end Alembic commands ###
