"""initial migration

Revision ID: a0e4b2c067
Revises: None
Create Date: 2015-04-13 00:04:18.577839

"""

# revision identifiers, used by Alembic.
revision = 'a0e4b2c067'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
